import os
from pathlib import Path

os.environ["USE_LIBUV"] = "0"

ROOT_DIR = Path(__file__).parent.absolute()
DATA_INPUT_DIR = ROOT_DIR / 'data_input'
PROJECT_OUTPUT_DIR = ROOT_DIR / 'output'

COCO_INPUT_DIR = DATA_INPUT_DIR / 'processed_taco_coco'
COCO_TRAIN_IMAGES = COCO_INPUT_DIR / 'train2017'
COCO_VAL_IMAGES = COCO_INPUT_DIR / 'val2017'
COCO_TRAIN_ANNOTATIONS = COCO_INPUT_DIR / 'annotations/instances_train2017.json'
COCO_VAL_ANNOTATIONS = COCO_INPUT_DIR / 'annotations/instances_val2017.json'

YOLO_GROUP_DIR = PROJECT_OUTPUT_DIR / 'YOLO'
YOLO_DATA_DIR = YOLO_GROUP_DIR / 'taco_yolo'
YOLO_TRAIN_IMAGES = YOLO_DATA_DIR / 'images/train'
YOLO_VAL_IMAGES = YOLO_DATA_DIR / 'images/val'
YOLO_TRAIN_LABELS = YOLO_DATA_DIR / 'labels/train'
YOLO_VAL_LABELS = YOLO_DATA_DIR / 'labels/val'
YOLO_CONFIG_FILE = YOLO_DATA_DIR / 'taco.yaml'
YOLO_FINETUNE_OUTPUT_DIR = YOLO_GROUP_DIR / 'yolo_checkpoints'

CONVNEXT_DISTILL_DIR = PROJECT_OUTPUT_DIR / 'DISTILL_CONVNEXT'
CONVNEXT_BEST_WEIGHTS = CONVNEXT_DISTILL_DIR / 'distilled_rtdetr_convnext_teacher_BEST.pth'
CONVNEXT_FINAL_WEIGHTS = CONVNEXT_DISTILL_DIR / 'distilled_rtdetr_convnext_teacher_FINAL.pth'

VIT_DISTILL_DIR = PROJECT_OUTPUT_DIR / 'DISTILL_VIT'
VIT_DISTILL_OUTPUT_DIR = VIT_DISTILL_DIR / 'distill_vit_lightly'
VIT_DISTILL_CHECKPOINTS_DIR = VIT_DISTILL_OUTPUT_DIR / 'checkpoints'
VIT_CONVERTED_WEIGHTS = VIT_DISTILL_DIR / 'distilled_rtdetr_vit_teacher_BEST.pth'

RTDETR_OUTPUT_DIR = PROJECT_OUTPUT_DIR / 'rtdetr' 
RTDETR_SOURCE_DIR = ROOT_DIR / 'rtdetr' 

CONFIG_GEN_DIR = PROJECT_OUTPUT_DIR / 'CONFIG'
RTDETR_FINETUNE_CONFIG_CONVNEXT = CONFIG_GEN_DIR / 'rtdetrv2_taco_finetune_convnext.yml'
RTDETR_FINETUNE_CONFIG_VIT = CONFIG_GEN_DIR / 'rtdetrv2_taco_finetune_vit.yml'
RTDETR_FINETUNE_CONFIG_BASELINE = CONFIG_GEN_DIR / 'rtdetrv2_taco_finetune_BASELINE.yml'

FINETUNE_BASELINE_OUTPUT_DIR = PROJECT_OUTPUT_DIR / 'FINETUNE_BASELINE'
FINETUNE_DISTILLED_OUTPUT_DIR = PROJECT_OUTPUT_DIR / 'FINETUNE_DISTILLED'

SCRIPTS_DIR = ROOT_DIR / 'scripts'
SRC_DIR = ROOT_DIR / 'src'

WANDB_PROJECT_CONVNEXT_DISTILL = "Distill-RTDETR-ConvNeXt-Teacher"
WANDB_PROJECT_VIT_DISTILL = "Distill-RTDETR-Distill-VIT"
WANDB_PROJECT_YOLO_FINETUNE = "yolo_runs_taco"

NUM_GPUS_PER_NODE = 1