__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/rtdetrv2_r50vd.yml',
]

output_dir: /kaggle/working/FINAL/FINETUNE_DISTILLED/rtdetrv2_finetune_taco_convnext_teacher

RTDETR:
  backbone: PResNet

PResNet:
  depth: 50
  variant: d
  freeze_at: 0
  return_idx: [1, 2, 3]
  num_stages: 4
  freeze_norm: True
  pretrained: False

task: detection
remap_mscoco_category: false
tuning: '/kaggle/working/FINAL/DISTILL-CONVNEXT/distilled_rtdetr_convnext_teacher_BEST.pth'
compile: true
epoches: 50

num_classes: 60

train_dataloader:
  num_workers: 4
  dataset:
    type: CocoDetection
    img_folder: /kaggle/input/dsp-pre-final/processed_taco_coco/train2017
    ann_file: /kaggle/input/dsp-pre-final/processed_taco_coco/annotations/instances_train2017.json

val_dataloader:
  num_workers: 4
  dataset:
    type: CocoDetection
    img_folder: /kaggle/input/dsp-pre-final/processed_taco_coco/val2017
    ann_file: /kaggle/input/dsp-pre-final/processed_taco_coco/annotations/instances_val2017.json

batch_size: 16

optimizer:
  type: AdamW
  params:
    - params: '^(?=.*backbone)'
      lr: 0.00001
    - params: '^(?=.*encoder)'
      lr: 0.00005
  lr: 0.0001
  weight_decay: 0.0001
  betas: [0.9, 0.999]

lr_scheduler:
  type: MultiStepLR
  milestones: [40]
  gamma: 0.1

checkpoint_freq: 10
